if(EXISTS "/Users/dannv/Workspace/SYSTEMS/emqx:clone/emqx-neuron/build-ninja/tests/ut/base64_test[1]_tests.cmake")
  include("/Users/dannv/Workspace/SYSTEMS/emqx:clone/emqx-neuron/build-ninja/tests/ut/base64_test[1]_tests.cmake")
else()
  add_test(base64_test_NOT_BUILT base64_test_NOT_BUILT)
endif()
