if(EXISTS "/Users/dannv/Workspace/SYSTEMS/emqx:clone/emqx-neuron/build-ninja/tests/ut/common_test[1]_tests.cmake")
  include("/Users/dannv/Workspace/SYSTEMS/emqx:clone/emqx-neuron/build-ninja/tests/ut/common_test[1]_tests.cmake")
else()
  add_test(common_test_NOT_BUILT common_test_NOT_BUILT)
endif()
