if(EXISTS "/Users/dannv/Workspace/SYSTEMS/emqx:clone/emqx-neuron/build-ninja/tests/ut/http_test[1]_tests.cmake")
  include("/Users/dannv/Workspace/SYSTEMS/emqx:clone/emqx-neuron/build-ninja/tests/ut/http_test[1]_tests.cmake")
else()
  add_test(http_test_NOT_BUILT http_test_NOT_BUILT)
endif()
