if(EXISTS "/Users/dannv/Workspace/SYSTEMS/emqx:clone/emqx-neuron/build-ninja/tests/ut/json_test[1]_tests.cmake")
  include("/Users/dannv/Workspace/SYSTEMS/emqx:clone/emqx-neuron/build-ninja/tests/ut/json_test[1]_tests.cmake")
else()
  add_test(json_test_NOT_BUILT json_test_NOT_BUILT)
endif()
