if(EXISTS "/Users/dannv/Workspace/SYSTEMS/emqx:clone/emqx-neuron/build-ninja/tests/ut/jwt_test[1]_tests.cmake")
  include("/Users/dannv/Workspace/SYSTEMS/emqx:clone/emqx-neuron/build-ninja/tests/ut/jwt_test[1]_tests.cmake")
else()
  add_test(jwt_test_NOT_BUILT jwt_test_NOT_BUILT)
endif()
