if(EXISTS "/Users/dannv/Workspace/SYSTEMS/emqx:clone/emqx-neuron/build-ninja/tests/ut/modbus_test[1]_tests.cmake")
  include("/Users/dannv/Workspace/SYSTEMS/emqx:clone/emqx-neuron/build-ninja/tests/ut/modbus_test[1]_tests.cmake")
else()
  add_test(modbus_test_NOT_BUILT modbus_test_NOT_BUILT)
endif()
