if(EXISTS "/Users/dannv/Workspace/SYSTEMS/emqx:clone/emqx-neuron/build-ninja/tests/ut/mqtt_client_test[1]_tests.cmake")
  include("/Users/dannv/Workspace/SYSTEMS/emqx:clone/emqx-neuron/build-ninja/tests/ut/mqtt_client_test[1]_tests.cmake")
else()
  add_test(mqtt_client_test_NOT_BUILT mqtt_client_test_NOT_BUILT)
endif()
